name: Test

on:
    push:

permissions: {}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install lix
              uses: canidae-solutions/lix-quick-install-action@0a4e78dfc0a3776603d255fa4a3c9860b7880167

            - name: Restore and save Nix store
              uses: nix-community/cache-nix-action@v7
              with:
                  primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
                  restore-prefixes-first-match: nix-${{ runner.os }}-

            - name: Build site
              run: nix build --print-build-logs
